/**
 * Url Shortener API
 * Url Shortener
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Link from './model/Link';
import RequestShortUrl from './model/RequestShortUrl';
import ResponseShortUrl from './model/ResponseShortUrl';
import DefaultApi from './api/DefaultApi';


/**
* Url_Shortener.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var UrlShortenerApi = require('index'); // See note below*.
* var xxxSvc = new UrlShortenerApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new UrlShortenerApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new UrlShortenerApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new UrlShortenerApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Link model constructor.
     * @property {module:model/Link}
     */
    Link,

    /**
     * The RequestShortUrl model constructor.
     * @property {module:model/RequestShortUrl}
     */
    RequestShortUrl,

    /**
     * The ResponseShortUrl model constructor.
     * @property {module:model/ResponseShortUrl}
     */
    ResponseShortUrl,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
