/**
 * Url Shortener API
 * Url Shortener
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UrlShortenerApi);
  }
}(this, function(expect, UrlShortenerApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UrlShortenerApi.Link();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Link', function() {
    it('should create an instance of Link', function() {
      // uncomment below and update the code to test Link
      //var instane = new UrlShortenerApi.Link();
      //expect(instance).to.be.a(UrlShortenerApi.Link);
    });

    it('should have the property token (base name: "token")', function() {
      // uncomment below and update the code to test the property token
      //var instance = new UrlShortenerApi.Link();
      //expect(instance).to.be();
    });

    it('should have the property targetUrl (base name: "targetUrl")', function() {
      // uncomment below and update the code to test the property targetUrl
      //var instance = new UrlShortenerApi.Link();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new UrlShortenerApi.Link();
      //expect(instance).to.be();
    });

    it('should have the property expiredAt (base name: "expiredAt")', function() {
      // uncomment below and update the code to test the property expiredAt
      //var instance = new UrlShortenerApi.Link();
      //expect(instance).to.be();
    });

    it('should have the property deletedAt (base name: "deletedAt")', function() {
      // uncomment below and update the code to test the property deletedAt
      //var instance = new UrlShortenerApi.Link();
      //expect(instance).to.be();
    });

    it('should have the property hits (base name: "hits")', function() {
      // uncomment below and update the code to test the property hits
      //var instance = new UrlShortenerApi.Link();
      //expect(instance).to.be();
    });

  });

}));
