/**
 * Url Shortener API
 * Url Shortener
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Link model module.
 * @module model/Link
 * @version 1.0.0
 */
class Link {
    /**
     * Constructs a new <code>Link</code>.
     * @alias module:model/Link
     * @param token {String} 
     * @param targetUrl {String} 
     * @param createdAt {Date} 
     * @param hits {Number} 
     */
    constructor(token, targetUrl, createdAt, hits) { 
        
        Link.initialize(this, token, targetUrl, createdAt, hits);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, token, targetUrl, createdAt, hits) { 
        obj['token'] = token;
        obj['targetUrl'] = targetUrl;
        obj['createdAt'] = createdAt;
        obj['hits'] = hits;
    }

    /**
     * Constructs a <code>Link</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Link} obj Optional instance to populate.
     * @return {module:model/Link} The populated <code>Link</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Link();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('targetUrl')) {
                obj['targetUrl'] = ApiClient.convertToType(data['targetUrl'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('expiredAt')) {
                obj['expiredAt'] = ApiClient.convertToType(data['expiredAt'], 'Date');
            }
            if (data.hasOwnProperty('deletedAt')) {
                obj['deletedAt'] = ApiClient.convertToType(data['deletedAt'], 'Date');
            }
            if (data.hasOwnProperty('hits')) {
                obj['hits'] = ApiClient.convertToType(data['hits'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} token
 */
Link.prototype['token'] = undefined;

/**
 * @member {String} targetUrl
 */
Link.prototype['targetUrl'] = undefined;

/**
 * @member {Date} createdAt
 */
Link.prototype['createdAt'] = undefined;

/**
 * @member {Date} expiredAt
 */
Link.prototype['expiredAt'] = undefined;

/**
 * @member {Date} deletedAt
 */
Link.prototype['deletedAt'] = undefined;

/**
 * @member {Number} hits
 */
Link.prototype['hits'] = undefined;






export default Link;

