/**
 * Url Shortener API
 * Url Shortener
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RequestShortUrl model module.
 * @module model/RequestShortUrl
 * @version 1.0.0
 */
class RequestShortUrl {
    /**
     * Constructs a new <code>RequestShortUrl</code>.
     * @alias module:model/RequestShortUrl
     * @param targetUrl {String} 
     */
    constructor(targetUrl) { 
        
        RequestShortUrl.initialize(this, targetUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, targetUrl) { 
        obj['targetUrl'] = targetUrl;
    }

    /**
     * Constructs a <code>RequestShortUrl</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RequestShortUrl} obj Optional instance to populate.
     * @return {module:model/RequestShortUrl} The populated <code>RequestShortUrl</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequestShortUrl();

            if (data.hasOwnProperty('targetUrl')) {
                obj['targetUrl'] = ApiClient.convertToType(data['targetUrl'], 'String');
            }
            if (data.hasOwnProperty('expiredInDays')) {
                obj['expiredInDays'] = ApiClient.convertToType(data['expiredInDays'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} targetUrl
 */
RequestShortUrl.prototype['targetUrl'] = undefined;

/**
 * @member {Number} expiredInDays
 */
RequestShortUrl.prototype['expiredInDays'] = undefined;






export default RequestShortUrl;

