/**
 * Url Shortener API
 * Url Shortener
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ResponseShortUrl model module.
 * @module model/ResponseShortUrl
 * @version 1.0.0
 */
class ResponseShortUrl {
    /**
     * Constructs a new <code>ResponseShortUrl</code>.
     * @alias module:model/ResponseShortUrl
     * @param shortUrl {String} 
     */
    constructor(shortUrl) { 
        
        ResponseShortUrl.initialize(this, shortUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, shortUrl) { 
        obj['shortUrl'] = shortUrl;
    }

    /**
     * Constructs a <code>ResponseShortUrl</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResponseShortUrl} obj Optional instance to populate.
     * @return {module:model/ResponseShortUrl} The populated <code>ResponseShortUrl</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResponseShortUrl();

            if (data.hasOwnProperty('shortUrl')) {
                obj['shortUrl'] = ApiClient.convertToType(data['shortUrl'], 'String');
            }
            if (data.hasOwnProperty('shortUrlInfo')) {
                obj['shortUrlInfo'] = ApiClient.convertToType(data['shortUrlInfo'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} shortUrl
 */
ResponseShortUrl.prototype['shortUrl'] = undefined;

/**
 * @member {String} shortUrlInfo
 */
ResponseShortUrl.prototype['shortUrlInfo'] = undefined;






export default ResponseShortUrl;

