shutdown-timeout: 30s
server:
  addr: ":8443"
  timeout: 3s
router:
  web-path: "web"
logging:
  path: "shurl.log"
  level: debug
  format: text
store:
  bolt:
    path: "data/links.db"
    timeout: 1s
tokenizer:
  hashid:
    salt: "ecafbaf0-1bcc-11ec-9621-0242ac130002"
    min-length: 5
    alphabet: "0123456789_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
